### ISSUE TITLE
Core dump after ^C when polling RTSP 

### ISSUE THREAD

**Issue by robotrapta** [groundlight/framegrab#18]
On Ubuntu 22.04 (arm64) with py3.10.12, when I have a simple app that polls an RTSP stream with framegrab, when I hit ^C it shows KeyboardInterrupt, but doesn't exit right away.  If I ^C again, I get this error:

```
KeyboardInterrupt
^CException ignored in: <module 'threading' from '/usr/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1567, in _shutdown
    lock.acquire()
KeyboardInterrupt:
terminate called without an active exception
Aborted (core dumped)
```

Core dumps indicate something fundamentally wrong.

**Comment by timmarkhuff** [comment]
This was resolved in https://github.com/groundlight/framegrab/commit/0549bb80b33116fb9aaa04878edd5b402fd602c3
