### ISSUE TITLE
Pypi page does not link to this repository

### ISSUE THREAD

**Issue by jones139** [groundlight/framegrab#19]
I have had a bit of trouble finding the source code repository- I could not find a link from https://pypi.org/project/framegrab/

**Comment by tyler-romero** [comment]
Thanks for the heads up! There is now a "Repository" link under "Project Links" on the pypi page.

**Comment by jones139** [comment]
Excellent, thank you for doing that so quickly - I don't know how to use pypi so I couldn't do you a pull request for it.
